### ISSUE TITLE
Non Functional Magnetic Sensor (Compass)

### ISSUE THREAD

**Issue by jonathandotchin** [ArrowOS-Devices/android_device_motorola_potter#16]
## Expected Behavior
The magnetic sensor (compass) should be working properly such that application like Google Maps can detect our heading.

## Current Behavior
The magnetic sensor (compass) seems to be turned off. In application like Google Maps, it is not able to detect our heading.

## Possible Solution
In Arrow OS 9, it seems to detect which version at the end of the install and applies the correct sensor. Perhaps, we can do the same here.

## Steps to Reproduce
1. Install Google Maps
2. Load Google Maps
3. Notice that Google Maps is unable to detect our heading (we only see a blue circle without direction)

## Context (Environment)
ArrowOS v10.0 Potter
August 9, 2020

**Comment by justks** [comment]
Hi, can you grab a logcat while trying that? My potter does not have a compass sensor so I was never aware whether compass was working or not until last week.

**Comment by justks** [comment]
open again with logcat
