### ISSUE TITLE
DIAG_CHAR Driver

### ISSUE THREAD

**Issue by ghost** [ArrowOS-Devices/android_device_motorola_potter#6]
Hello,

I'm hoping this is the right place for this. Would it be possible to enable DIAG_CHAR in the kernel for SnoopSnitch and radio debugging? Seems that this driver is the only missing piece halting SnoopSnitch's full functionality. 

https://opensource.srlabs.de/projects/snoopsnitch

Thank you for all of your hard work on ArrowOS and the support for this device. :)

**Comment by justks** [comment]
Interesting, but i am not really sure i need to have to enable additional debugging for some "test" app because that's not something i wanna do.

**Comment by ghost** [comment]
Basically, it's used for trying to determine if you're connected to a legit cell tower or some kind of IMSI-catcher. Ones like the [StingRay](https://en.wikipedia.org/wiki/Stingray_phone_tracker) are getting more and more common these days, and really, anyone can get one if they have the funds. SnoopSnitch can help verify your connection to your provider. 

Certainly not necessary to have it enabled, but also a huge win for the Privacy/Security-minded users.
